### ISSUE TITLE
catkin_make failed

### ISSUE THREAD

**Issue by zhouziling** [ZiqiChai/k4a-ros#1]
hello! I found make failed because of "no file named  #include "turbojpeg.h"

**Comment by ZiqiChai** [comment]
That seems to be the missing library of "libjpeg-turbo".
And you can fix it by install "libjpeg-turbo" at "https://github.com/libjpeg-turbo/libjpeg-turbo"

**Comment by ZiqiChai** [comment]
> hello! I found make failed because of "no file named #include "turbojpeg.h"

That seems to be the missing library of "libjpeg-turbo".
And you can fix it by install "libjpeg-turbo" at "https://github.com/libjpeg-turbo/libjpeg-turbo"
